# Stubs for tensorflow.errors (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tensorflow.python import OpError as OpError
from tensorflow.python.framework.errors import AbortedError as AbortedError, AlreadyExistsError as AlreadyExistsError, CancelledError as CancelledError, DataLossError as DataLossError, DeadlineExceededError as DeadlineExceededError, FailedPreconditionError as FailedPreconditionError, InternalError as InternalError, InvalidArgumentError as InvalidArgumentError, NotFoundError as NotFoundError, OutOfRangeError as OutOfRangeError, PermissionDeniedError as PermissionDeniedError, ResourceExhaustedError as ResourceExhaustedError, UnauthenticatedError as UnauthenticatedError, UnavailableError as UnavailableError, UnimplementedError as UnimplementedError, UnknownError as UnknownError, error_code_from_exception_type as error_code_from_exception_type, exception_type_from_error_code as exception_type_from_error_code, raise_exception_on_not_ok_status as raise_exception_on_not_ok_status
from tensorflow.python.framework.errors_impl import ABORTED as ABORTED, ALREADY_EXISTS as ALREADY_EXISTS, CANCELLED as CANCELLED, DATA_LOSS as DATA_LOSS, DEADLINE_EXCEEDED as DEADLINE_EXCEEDED, FAILED_PRECONDITION as FAILED_PRECONDITION, INTERNAL as INTERNAL, INVALID_ARGUMENT as INVALID_ARGUMENT, NOT_FOUND as NOT_FOUND, OK as OK, OUT_OF_RANGE as OUT_OF_RANGE, PERMISSION_DENIED as PERMISSION_DENIED, RESOURCE_EXHAUSTED as RESOURCE_EXHAUSTED, UNAUTHENTICATED as UNAUTHENTICATED, UNAVAILABLE as UNAVAILABLE, UNIMPLEMENTED as UNIMPLEMENTED, UNKNOWN as UNKNOWN
